FROM scratch

COPY test_network/accounts.json /accounts.json
COPY test_network/docker-compose.yml /docker-compose.yml
COPY test_network/ledger.json /ledger.json
COPY test_network/sidecar /sidecar
COPY test_network/volumes /volumes
COPY test_network/workload /workload
