FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.7.21 /uv /uvx /bin/

ENV PYTHONUNBUFFERED=1
WORKDIR /opt/antithesis/catalog/workload
COPY workload /opt/antithesis/catalog/workload

# TODO: Update when buildkit available
# RUN --mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
#     uv sync
RUN uv sync
COPY test_composer/tc_commands /opt/antithesis/catalog/tc_commands

COPY test_composer/all_transactions /opt/antithesis/test/v1/all_transactions
# COPY accounts.json /opt/antithesis/workload.json

ENV PATH="/opt/antithesis/catalog/workload/.venv/bin:/opt/antithesis/test/v1/all_transactions:$PATH"

CMD ["uv", "run", "workload"]
