#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/../workload"

echo "Checking all workload imports..."
uv run python -c "
from workload.app import main
from workload.transactions.credentials import credential_create, credential_accept, credential_delete
from workload.transactions.vaults import vault_create, vault_deposit, vault_withdraw, vault_set, vault_delete, vault_clawback
from workload.transactions.domains import permissioned_domain_set, permissioned_domain_delete
from workload.transactions.delegation import delegate_set
from workload.transactions.amm import amm_create, amm_deposit, amm_withdraw, amm_vote, amm_bid, amm_delete
from workload.transactions.mpt import mpt_create, mpt_authorize, mpt_issuance_set, mpt_destroy
from workload.transactions.nft import nftoken_mint, nftoken_modify
from workload.transactions.offers import offer_create, offer_cancel
from workload.transactions.lending import (
    loan_broker_set, loan_broker_delete,
    loan_broker_cover_deposit, loan_broker_cover_withdraw,
    loan_set, loan_delete, loan_manage, loan_pay,
)
from workload.assertions import tx_submitted, tx_result, register_assertions
from workload.submit import submit_tx
from workload.sequence import SequenceTracker
from workload.ws_listener import start_ws_listener
from workload.setup import run_setup
from workload.params import should_send_faulty, fake_account, fake_id
from workload.models import UserAccount, Credential, Vault, PermissionedDomain, MPTokenIssuance, LoanBroker, Loan, Delegate
print('All imports OK')
"
