include:
  - xrpl_net.yml
services:
  workload:
    image: WORKLOAD_IMAGE
    container_name: workload
    hostname: workload
    networks:
      xrpl_net:
    depends_on:
      rippled:
        condition: service_healthy
